server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql:3308/cloud_user?useSSL=false
    username: root
    password: 291415
    driver-class-name: com.mysql.jdbc.Driver
    # 在nacos配置文件中已经有了
#  application:
#    name: userservice # user服务的服务名称
#  cloud:
#    nacos:
#      server-addr: localhost:8848  # nacos服务地址
#      discovery:
#        cluster-name: HZ
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
pattern:
  name: 本地环境local